# Generated by Django 4.2.4 on 2023-09-04 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_blograting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('MachineLearning', 'Machine Learning'), ('News', 'News'), ('Sports', 'Sports'), ('Test', 'Test')], max_length=100),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(upload_to='photos/blog'),
        ),
    ]
